version: '3'
services:
  express-app:
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - PORT=5001
    depends_on:
      - mongo-db
    networks:
      - mynetwork

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=brandShopDB
    volumes:
      - mongodb-data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb-data:
